import { Hand } from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * A brief with no `briefScheduleId` was generated by hand from the generate
 * dialog — nothing will recreate it, which is also why it is the only kind
 * that can be deleted.
 */
export function OneOffBadge({ className }: { className?: string }) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full border border-border px-2.5 py-0.5 font-mono text-xs uppercase tracking-[0.05em] text-muted-foreground",
        className,
      )}
    >
      <Hand className="size-3" />
      One-off
    </span>
  );
}
